#DataBaseHost = "192.168.1.10:9000"
DataBaseHost = "127.0.0.1:9000"
DataBaseName = "default"
DataBaseUser = "default"
DataBasePass = ""
TableName = "tron_accounts_35"
WorkerNum = 32
BathNum = 10000
TimeWait = 1