// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: enode.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StartStreamReq) Reset() {
	*x = StartStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamReq) ProtoMessage() {}

func (x *StartStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_enode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamReq.ProtoReflect.Descriptor instead.
func (*StartStreamReq) Descriptor() ([]byte, []int) {
	return file_enode_proto_rawDescGZIP(), []int{0}
}

func (x *StartStreamReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartStreamRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamType int32  `protobuf:"varint,1,opt,name=streamType,proto3" json:"streamType,omitempty"` // 1:Block 2:Tx
	StartTiem  int64  `protobuf:"varint,2,opt,name=startTiem,proto3" json:"startTiem,omitempty"`
	Msg        []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"` //block或者tx二进制信息
}

func (x *StartStreamRes) Reset() {
	*x = StartStreamRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enode_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartStreamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamRes) ProtoMessage() {}

func (x *StartStreamRes) ProtoReflect() protoreflect.Message {
	mi := &file_enode_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamRes.ProtoReflect.Descriptor instead.
func (*StartStreamRes) Descriptor() ([]byte, []int) {
	return file_enode_proto_rawDescGZIP(), []int{1}
}

func (x *StartStreamRes) GetStreamType() int32 {
	if x != nil {
		return x.StreamType
	}
	return 0
}

func (x *StartStreamRes) GetStartTiem() int64 {
	if x != nil {
		return x.StartTiem
	}
	return 0
}

func (x *StartStreamRes) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type SendTxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TxHex [][]byte `protobuf:"bytes,2,rep,name=txHex,proto3" json:"txHex,omitempty"` //tx二进制信息
}

func (x *SendTxReq) Reset() {
	*x = SendTxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enode_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTxReq) ProtoMessage() {}

func (x *SendTxReq) ProtoReflect() protoreflect.Message {
	mi := &file_enode_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTxReq.ProtoReflect.Descriptor instead.
func (*SendTxReq) Descriptor() ([]byte, []int) {
	return file_enode_proto_rawDescGZIP(), []int{2}
}

func (x *SendTxReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendTxReq) GetTxHex() [][]byte {
	if x != nil {
		return x.TxHex
	}
	return nil
}

type SendTxToCoinBaseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CoinBaseName string   `protobuf:"bytes,2,opt,name=coinBaseName,proto3" json:"coinBaseName,omitempty"`
	Top          int32    `protobuf:"varint,3,opt,name=top,proto3" json:"top,omitempty"`
	TxHex        [][]byte `protobuf:"bytes,4,rep,name=txHex,proto3" json:"txHex,omitempty"` //tx二进制信息
}

func (x *SendTxToCoinBaseReq) Reset() {
	*x = SendTxToCoinBaseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enode_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTxToCoinBaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTxToCoinBaseReq) ProtoMessage() {}

func (x *SendTxToCoinBaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_enode_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTxToCoinBaseReq.ProtoReflect.Descriptor instead.
func (*SendTxToCoinBaseReq) Descriptor() ([]byte, []int) {
	return file_enode_proto_rawDescGZIP(), []int{3}
}

func (x *SendTxToCoinBaseReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendTxToCoinBaseReq) GetCoinBaseName() string {
	if x != nil {
		return x.CoinBaseName
	}
	return ""
}

func (x *SendTxToCoinBaseReq) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *SendTxToCoinBaseReq) GetTxHex() [][]byte {
	if x != nil {
		return x.TxHex
	}
	return nil
}

type SendTxRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SendTxRes) Reset() {
	*x = SendTxRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_enode_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTxRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTxRes) ProtoMessage() {}

func (x *SendTxRes) ProtoReflect() protoreflect.Message {
	mi := &file_enode_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTxRes.ProtoReflect.Descriptor instead.
func (*SendTxRes) Descriptor() ([]byte, []int) {
	return file_enode_proto_rawDescGZIP(), []int{4}
}

func (x *SendTxRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_enode_proto protoreflect.FileDescriptor

var file_enode_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a,
	0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x35, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x78, 0x48, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x78, 0x48, 0x65, 0x78, 0x22, 0x75, 0x0a, 0x13,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x54, 0x6f, 0x43, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x69, 0x6e, 0x42,
	0x61, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63,
	0x6f, 0x69, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x6f, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x78, 0x48, 0x65, 0x78, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x78,
	0x48, 0x65, 0x78, 0x22, 0x23, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x52, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xb4, 0x01, 0x0a, 0x15, 0x45, 0x6e, 0x6f,
	0x64, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x12, 0x37, 0x0a, 0x0f, 0x68, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x26, 0x0a, 0x0a, 0x68,
	0x61, 0x6e, 0x64, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x12, 0x0a, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x54, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x14, 0x68, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x78, 0x54, 0x6f, 0x43, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x12, 0x14, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x54, 0x78, 0x54, 0x6f, 0x43, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x0a, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x78, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42,
	0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_enode_proto_rawDescOnce sync.Once
	file_enode_proto_rawDescData = file_enode_proto_rawDesc
)

func file_enode_proto_rawDescGZIP() []byte {
	file_enode_proto_rawDescOnce.Do(func() {
		file_enode_proto_rawDescData = protoimpl.X.CompressGZIP(file_enode_proto_rawDescData)
	})
	return file_enode_proto_rawDescData
}

var file_enode_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_enode_proto_goTypes = []interface{}{
	(*StartStreamReq)(nil),      // 0: StartStreamReq
	(*StartStreamRes)(nil),      // 1: StartStreamRes
	(*SendTxReq)(nil),           // 2: SendTxReq
	(*SendTxToCoinBaseReq)(nil), // 3: SendTxToCoinBaseReq
	(*SendTxRes)(nil),           // 4: SendTxRes
}
var file_enode_proto_depIdxs = []int32{
	0, // 0: EnodeManagerInterface.handStartStream:input_type -> StartStreamReq
	2, // 1: EnodeManagerInterface.handSendTx:input_type -> SendTxReq
	3, // 2: EnodeManagerInterface.handSendTxToCoinBase:input_type -> SendTxToCoinBaseReq
	1, // 3: EnodeManagerInterface.handStartStream:output_type -> StartStreamRes
	4, // 4: EnodeManagerInterface.handSendTx:output_type -> SendTxRes
	4, // 5: EnodeManagerInterface.handSendTxToCoinBase:output_type -> SendTxRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enode_proto_init() }
func file_enode_proto_init() {
	if File_enode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_enode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enode_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartStreamRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enode_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enode_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTxToCoinBaseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_enode_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTxRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_enode_proto_goTypes,
		DependencyIndexes: file_enode_proto_depIdxs,
		MessageInfos:      file_enode_proto_msgTypes,
	}.Build()
	File_enode_proto = out.File
	file_enode_proto_rawDesc = nil
	file_enode_proto_goTypes = nil
	file_enode_proto_depIdxs = nil
}
